import { existsSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Share, ServicesConfig } from "@opennas/shared";
import { config } from "../config.js";
import { getSetting, setSetting } from "../db/settings.js";
import { listShares } from "../db/shares.js";
import { isValidNfsClient } from "../db/nfs-rules.js";

const DEFAULT: ServicesConfig = {
  smb: { enabled: false, workgroup: "WORKGROUP", serverString: "OpenNAS", allowGuest: false },
  nfs: { enabled: false, allowedNetworks: "" },
  afp: { enabled: false },
};

export function getServicesConfig(): ServicesConfig {
  const raw = getSetting("services");
  if (!raw) return DEFAULT;
  try {
    const parsed = JSON.parse(raw) as Partial<ServicesConfig>;
    return {
      smb: { ...DEFAULT.smb, ...parsed.smb },
      nfs: { ...DEFAULT.nfs, ...parsed.nfs },
      afp: { ...DEFAULT.afp, ...parsed.afp },
    };
  } catch {
    return DEFAULT;
  }
}

export interface ServicesConfigPatch {
  smb?: Partial<ServicesConfig["smb"]>;
  nfs?: Partial<ServicesConfig["nfs"]>;
  afp?: Partial<ServicesConfig["afp"]>;
}

export function setServicesConfig(partial: ServicesConfigPatch): ServicesConfig {
  const current = getServicesConfig();
  const next: ServicesConfig = {
    smb: { ...current.smb, ...partial.smb },
    nfs: { ...current.nfs, ...partial.nfs },
    afp: { ...current.afp, ...partial.afp },
  };
  setSetting("services", JSON.stringify(next));
  return next;
}

/**
 * Absolute on-disk path for a share. Shares placed on a data volume live under
 * `<volumesRoot>/<label>/<name>`; otherwise under the default share root. This is
 * the single source of truth for where a share's files are - used for the daemon
 * configs here and for directory creation / sizing in the admin routes.
 */
export function shareBasePath(share: Pick<Share, "name" | "volume">): string {
  if (share.volume) return join(config.volumesRoot, share.volume, share.name);
  return join(config.filesRoot, share.name);
}

/** Render an /etc/samba/smb.conf that mirrors the current shares & settings. */
export function generateSmbConf(cfg: ServicesConfig, shares: Share[]): string {
  const lines: string[] = [
    "# Generated by OpenNAS - do not edit by hand.",
    "[global]",
    `   workgroup = ${cfg.smb.workgroup || "WORKGROUP"}`,
    `   server string = ${cfg.smb.serverString || "OpenNAS"}`,
    "   security = user",
    `   map to guest = ${cfg.smb.allowGuest ? "Bad User" : "Never"}`,
    // Extended attributes are what `fruit` stores macOS metadata in; without
    // them Time Machine fails partway through rather than refusing up front.
    "   ea support = yes",
    "   vfs objects = catia fruit streams_xattr",
    // The standard fruit recipe. `model` is what makes macOS show the NAS with
    // a server icon instead of a generic one; the rest keep AppleDouble
    // sidecar files from littering shares that Windows and Linux also use.
    "   fruit:aapl = yes",
    "   fruit:metadata = stream",
    "   fruit:model = MacSamba",
    "   fruit:posix_rename = yes",
    "   fruit:veto_appledouble = no",
    "   fruit:wipe_intentionally_left_blank_rfork = yes",
    "   fruit:delete_empty_adfiles = yes",
    "",
  ];

  for (const s of shares.filter((x) => x.smbEnabled)) {
    // Groups go in as `@name`, which Samba resolves through the system group
    // database - `syncShareGroup` is what keeps that in step. Listing the group
    // rather than expanding its members means adding someone to a group takes
    // effect without rewriting every share they should now reach.
    const groupWriters = s.groupPermissions.filter((g) => g.level === "rw").map((g) => `@${g.name}`);
    const groupReaders = s.groupPermissions.map((g) => `@${g.name}`);
    const writers = [...s.permissions.filter((p) => p.level === "rw").map((p) => p.username), ...groupWriters];
    const readers = [...s.permissions.map((p) => p.username), ...groupReaders];
    const guest = s.guestAccess; // none | ro | rw
    // Who can connect (read) and who can write. Guests map to the "nobody" user.
    const validUsers = guest !== "none" ? [...readers, "nobody"] : [...readers];
    const writeList = guest === "rw" ? [...writers, "nobody"] : [...writers];
    lines.push(
      `[${s.name}]`,
      `   path = ${shareBasePath(s)}`,
      s.comment ? `   comment = ${s.comment}` : "   comment =",
      `   browseable = ${s.browseable ? "yes" : "no"}`,
      // Deny writes by default; grant write ONLY to users in "write list". This is
      // what makes a user set to read-only stay read-only even when another user
      // on the same share has read-write (with `read only = no`, Samba lets every
      // valid user write regardless of the write list - the bug this fixes).
      "   read only = yes",
      `   guest ok = ${guest !== "none" ? "yes" : "no"}`,
      validUsers.length ? `   valid users = ${validUsers.join(" ")}` : "   valid users =",
      writeList.length ? `   write list = ${writeList.join(" ")}` : "   write list =",
    );
    // The share data is owned by the OpenNAS service account, but each SMB user
    // authenticates as their own (login-less) system user. Without force user the
    // kernel would deny them access to the service-owned tree - the share mounts
    // but nothing inside is readable/writable. Map every connection to the owning
    // account so granted users can actually use the folder.
    if (config.shareOwner) {
      lines.push(`   force user = ${config.shareOwner}`, `   force group = ${config.shareOwner}`);
    }
    // `vfs objects` is a whole-list setting, not additive: a second line in the
    // same section replaces the first rather than extending it. Recycle and
    // Time Machine both need modules, so the list is composed once here - two
    // separate `vfs objects` lines would silently drop whichever came first.
    const vfsObjects = ["catia", "fruit", "streams_xattr"];
    if (s.recycleEnabled) vfsObjects.push("recycle");
    lines.push(`   vfs objects = ${vfsObjects.join(" ")}`);

    // Per-share recycle bin. Without it a delete over SMB is final, while the
    // same delete in the web UI is recoverable - the same folder behaving two
    // different ways depending on how you reached it.
    if (s.recycleEnabled) {
      lines.push(
        "   recycle:repository = .recycle/%U",
        "   recycle:keeptree = yes",
        "   recycle:versions = yes",
        // Don't resurrect the things nobody wants back.
        "   recycle:exclude = *.tmp|*.temp|*.o|*.obj|~$*|*.~??",
        "   recycle:exclude_dir = /tmp|/cache",
        "   recycle:touch = no",
        "   recycle:directory_mode = 0775",
      );
    }
    // Time Machine. Only meaningful once the share is reachable and private:
    // macOS refuses a guest-accessible destination, so an operator who ticked
    // both would otherwise get a share that simply never appears in the
    // Time Machine picker with nothing explaining why.
    if (s.timeMachineEnabled && s.guestAccess === "none") {
      lines.push("   fruit:time machine = yes");
      // Passed to macOS so it plans its own retention and stops cleanly. Without
      // it Time Machine grows until the volume is full and fails mid-backup,
      // taking every other share on that volume down with it.
      if (s.quotaBytes > 0) {
        lines.push(`   fruit:time machine max size = ${Math.floor(s.quotaBytes / 1024)}K`);
      }
    }
    lines.push("   create mask = 0664", "   directory mask = 0775", "");
  }
  return lines.join("\n");
}

/**
 * Render an /etc/exports for NFS-enabled shares.
 *
 * A share with its own rules uses only those. A share without them keeps exactly
 * the old behaviour - the global network list, at `rw` if guest access is
 * read-write and `ro` otherwise.
 *
 * Tying NFS write access to `guestAccess` is wrong on the face of it: that is an
 * SMB setting and NFS has no guests. But it is the behaviour every existing
 * installation is running on, and quietly turning someone's working NFS export
 * read-only during an upgrade is a worse problem than the one it fixes. So the
 * fallback is left alone and per-share rules are purely additive: add one and
 * the share stops inheriting anything.
 *
 * Every client spec is re-validated here even though the database only accepts
 * valid ones. This function's output is a config file where a stray space makes
 * one rule into two and a newline appends rules nobody asked for, so it does not
 * rely on having been the only way in.
 */
export function generateExports(cfg: ServicesConfig, shares: Share[]): string {
  const globalNets = (cfg.nfs.allowedNetworks || "*")
    .split(",")
    .map((n) => n.trim())
    .filter((n) => n.length > 0 && isValidNfsClient(n));
  const fallback = globalNets.length ? globalNets : ["*"];

  const lines: string[] = ["# Generated by OpenNAS - do not edit by hand."];
  for (const s of shares.filter((x) => x.nfsEnabled)) {
    const rules = s.nfsRules.filter((r) => isValidNfsClient(r.network));
    const inheritedLevel = s.guestAccess === "rw" ? "rw" : "ro";
    const specs = rules.length
      ? rules.map((r) => `${r.network}(${exportOptions(r.level, r.rootSquash)})`)
      : fallback.map((c) => `${c}(${exportOptions(inheritedLevel, true)})`);
    if (specs.length === 0) continue;
    lines.push(`${shareBasePath(s)}    ${specs.join(" ")}`);
  }
  return lines.join("\n") + "\n";
}

function exportOptions(level: "ro" | "rw", rootSquash: boolean): string {
  // `sync` so a client's write is on disk before it is acknowledged, and
  // `no_subtree_check` because subtree checking breaks renames on an exported
  // subdirectory for no security benefit worth having.
  return [level, "sync", "no_subtree_check", rootSquash ? "root_squash" : "no_root_squash"].join(",");
}

/**
 * Render the mDNS advertisement that makes macOS *offer* a share as a Time
 * Machine destination.
 *
 * Reachability alone isn't enough: without an `_adisk._tcp` record the share
 * mounts fine but never appears in Time Machine's destination picker, which
 * looks exactly like the feature being broken. Samba publishes `_smb._tcp`
 * itself, so only this record is generated here - duplicating the other would
 * put two advertisements for one service on the network.
 *
 * Returns an empty string when no share wants it, so the file can be truncated
 * rather than left advertising a destination that no longer exists.
 */
export function generateTimeMachineAvahi(cfg: ServicesConfig, shares: Share[]): string {
  // Guest-accessible shares are excluded for the same reason smb.conf skips
  // them: macOS refuses a destination anyone can reach.
  const targets = cfg.smb.enabled
    ? shares.filter((s) => s.timeMachineEnabled && s.smbEnabled && s.guestAccess === "none")
    : [];
  if (targets.length === 0) return "";

  const disks = targets.map((s, i) =>
    // adVF=0x82 marks the volume as a Time Machine target that supports the
    // modern (SMB) protocol; adVN carries the share name macOS should mount.
    `    <txt-record>dk${i}=adVN=${escapeXml(s.name)},adVF=0x82</txt-record>`,
  );

  return `<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<!--
  Generated by OpenNAS - do not edit by hand.
  Rewritten whenever shares or file services change.
-->
<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_adisk._tcp</type>
    <!-- _adisk carries no connection of its own; macOS reads the records and
         then connects over SMB. Port 9 (discard) is the convention. -->
    <port>9</port>
    <txt-record>sys=waMa=0,adVF=0x100</txt-record>
${disks.join("\n")}
  </service>
</service-group>
`;
}

function escapeXml(v: string): string {
  return v.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/**
 * Regenerate every file-sharing config from the current shares + settings and
 * write it out. Always mirrored into the data dir; also written straight to the
 * real daemon paths when those are configured and writable. Called automatically
 * whenever shares or services change, so a new share is wired up end-to-end with
 * no manual copy/paste. Best-effort: failures are logged, never thrown.
 */
export function applyGeneratedConfigs(log?: { warn: (o: unknown, m?: string) => void }): void {
  const cfg = getServicesConfig();
  const shares = listShares();
  const smbConf = generateSmbConf(cfg, shares);
  const exports = generateExports(cfg, shares);
  const timeMachine = generateTimeMachineAvahi(cfg, shares);

  const targets: { path: string; content: string }[] = [
    { path: join(config.generatedDir, "smb.conf"), content: smbConf },
    { path: join(config.generatedDir, "exports"), content: exports },
  ];
  if (config.smbConfPath) targets.push({ path: config.smbConfPath, content: smbConf });
  if (config.nfsExportsPath) targets.push({ path: config.nfsExportsPath, content: exports });

  for (const t of targets) {
    try {
      writeFileSync(t.path, t.content, "utf8");
    } catch (err) {
      log?.warn({ err, path: t.path }, "could not write generated share config");
    }
  }

  // The Time Machine advertisement is removed rather than blanked when no share
  // wants it: avahi parses every file in its services directory and an empty
  // one is a parse error it complains about on each reload, so a truncated file
  // would leave the log permanently noisy for a feature nobody enabled.
  for (const path of [
    join(config.generatedDir, "opennas-timemachine.service"),
    config.timeMachineAvahiPath,
  ]) {
    if (!path) continue;
    try {
      if (timeMachine) writeFileSync(path, timeMachine, "utf8");
      else rmSync(path, { force: true });
    } catch (err) {
      log?.warn({ err, path }, "could not update the Time Machine advertisement");
    }
  }
}

/** Best-effort detection of installed file-sharing daemons. */
export function detectDaemons(): { smbd: boolean; nfsd: boolean; afpd: boolean } {
  const any = (paths: string[]) => paths.some((p) => existsSync(p));
  return {
    smbd: any(["/usr/sbin/smbd", "/usr/bin/smbd", "/usr/local/sbin/smbd"]),
    nfsd: any(["/usr/sbin/rpc.nfsd", "/proc/fs/nfsd", "/usr/sbin/exportfs"]),
    afpd: any(["/usr/sbin/afpd", "/usr/bin/afpd", "/usr/sbin/netatalk", "/usr/bin/netatalk"]),
  };
}
